site_name: libvcell
repo_url: https://github.com/virtualcell/libvcell
site_url: https://virtualcell.github.io/libvcell
site_description: This is a python package which wraps a subset of VCell Java code as a native python package.
site_author: Jim Schaff
edit_uri: edit/main/docs/
repo_name: virtualcell/libvcell
copyright: Maintained by <a href="https://virtualcell.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/virtualcell/libvcell
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/libvcell

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
