FROM quay.io/pypa/manylinux_2_28_x86_64

WORKDIR /opt

# install graalvm community edition
RUN export GRAALVM_VERSION=23.0.2 && \
    export MAVEN_VERSION=3.9.9 && \
    export ARCH=x86_64 && \
    curl -L -o graalvm.tar.gz https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-${GRAALVM_VERSION}/graalvm-community-jdk-${GRAALVM_VERSION}_linux-${ARCH}_bin.tar.gz && \
    tar -xzf graalvm.tar.gz && \
    export GRAALVM_HOME="$(cd "$(ls | grep "$GRAALVM_VERSION" | grep graalvm)" && pwd)" && \
    echo "export JAVA_HOME=$GRAALVM_HOME" >> ~/.bashrc && \
    echo "export GRAALVM_HOME=$GRAALVM_HOME" >> ~/.bashrc && \
    echo "export PATH=$GRAALVM_HOME/bin:\$PATH" >> ~/.bashrc

# install Poetry
RUN curl -sSL https://install.python-poetry.org | python3 - && \
    echo "export PATH=~/.local/bin:\$PATH" >> ~/.bashrc

    # Install Maven
RUN export MAVEN_VERSION=3.9.9 && \
    curl -L -o apache-maven.tar.gz https://dlcdn.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz && \
    tar -xzf apache-maven.tar.gz && \
    export MAVEN_HOME="$(cd "$(ls | grep "$MAVEN_VERSION" | grep maven)" && pwd)" && \
    echo "export MAVEN_HOME=$MAVEN_HOME" >> ~/.bashrc && \
    echo "export PATH=$MAVEN_HOME/bin:\$PATH" >> ~/.bashrc
