FROM quay.io/pypa/manylinux_2_34_x86_64

ARG GRAALVM_VERSION=23.0.2
ARG GRAALVM_BUILD=7.1
ARG GRAALVM_ARCH=x64
ARG MAVEN_VERSION=3.9.15

# install graalvm community edition
RUN cd /opt && \
    curl -L -o graalvm.tar.gz https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-${GRAALVM_VERSION}/graalvm-community-jdk-${GRAALVM_VERSION}_linux-${GRAALVM_ARCH}_bin.tar.gz && \
    tar -xzf graalvm.tar.gz
ENV GRAALVM_HOME=/opt/graalvm-community-openjdk-${GRAALVM_VERSION}+${GRAALVM_BUILD}
ENV JAVA_HOME=${GRAALVM_HOME}
ENV PATH=${GRAALVM_HOME}/bin:$PATH

# install Poetry
RUN dnf install python3.13 -y
RUN ln -s /usr/local/bin/python3.13 /usr/local/bin/python3
RUN (curl -sSL https://install.python-poetry.org | python3 -) || ( echo "" && echo "" && echo "" && echo 'LogContents:' && cat /poetry-installer-error-*.log && exit 1)
ENV PATH=~/.local/bin:$PATH

# Install Maven

RUN cd /opt && curl -L -o apache-maven.tar.gz https://dlcdn.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz && ls && tar -xzvf apache-maven.tar.gz
ENV MAVEN_HOME=/opt/apache-maven-${MAVEN_VERSION}
ENV PATH=${MAVEN_HOME}/bin:$PATH
