# build and publish custom manylinux with GraalVM, Maven, and Poetry
name: Docker
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the Many-Linux Docker image"
        required: true

jobs:
  login:
    strategy:
      matrix:
        arch:
          - os: ubuntu-latest
            type: x86_64
          - os: ubuntu-24.04-arm
            type: aarch64
        glibc: [2_28, 2_34]
    runs-on: ${{ matrix.arch.os }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Maven Version
        run: |
          MAVEN_VERSION="$(curl -s https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/ | grep -o '3\.9\.[0-9]*' | sort -V | tail -1)"
          if [ -z "${MAVEN_VERSION}" ]; then
            echo "No valid maven version of 3.9.X found!"
            exit 1
          fi
          echo "MAVEN_VERSION=${MAVEN_VERSION}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: docker
          file: docker/Dockerfile_manylinux_${{ matrix.glibc }}_${{ matrix.arch.type }}
          push: true
          build-args: |
            MAVEN_VERSION=${{ env.MAVEN_VERSION }}
          tags: |
            ghcr.io/virtualcell/manylinux_${{ matrix.glibc }}_${{ matrix.arch.type }}:${{ github.event.inputs.tag }}
            ghcr.io/virtualcell/manylinux_${{ matrix.glibc }}_${{ matrix.arch.type }}:latest
