name: Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env

      - name: Run checks
        run: make check

  tests-and-type-check:
    runs-on: ubuntu-latest
    strategy:
      matrix: #        python-version: ["3.9", "3.10", "3.11", "3.12"]
        python-version: ["3.11", "3.12"]
        #        os: [macos-13, windows-latest, ubuntu-latest, macos-14]
        os: [windows-latest, ubuntu-latest, macos-14]
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 2

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env
        with:
          python-version: ${{ matrix.python-version }}

      - name: setup graalvm for static native build
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: "23"
          distribution: "graalvm-community"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          components: "native-image"
          #          native-image-musl: 'true' # Now semi-static by not including libc
          native-image-job-reports: "true"
          cache: "maven"

      - name: build entire project
        working-directory: vcell_submodule
        run: |
          mvn --batch-mode clean install dependency:copy-dependencies -DskipTests=true

      - name: test, record, and build/install native library (ubuntu)
        working-directory: vcell-native
        run: |
          mvn --batch-mode clean install

          java -agentlib:native-image-agent=config-output-dir=target/recording \
               -jar target/vcell-native-1.0-SNAPSHOT.jar \
               "src/test/resources/TinySpacialProject_Application0.xml" \
               "target/sbml-input"

          mvn --batch-mode -P shared-dll package
          cp target/libvcell.so ../libvcell/_internal/libs
        if: ${{ startsWith(matrix.os, 'ubuntu') }}

      - name: test, record, and build/install native library (macos)
        working-directory: vcell-native
        run: |
          mvn --batch-mode clean install

          java -agentlib:native-image-agent=config-output-dir=target/recording \
               -jar target/vcell-native-1.0-SNAPSHOT.jar \
               "src/test/resources/TinySpacialProject_Application0.xml" \
               "target/sbml-input"

          mvn --batch-mode -P shared-dll package
          cp target/libvcell.dylib ../libvcell/_internal/libs
        if: ${{ startsWith(matrix.os, 'macos') }}

      - name: test, record, and build/install native library (windows)
        working-directory: vcell-native
        run: |
          mvn --batch-mode clean install

          java -agentlib:native-image-agent=config-output-dir=target\recording -jar "target\vcell-native-1.0-SNAPSHOT.jar" "src\test\resources\TinySpacialProject_Application0.xml" "target\sbml-input"

          mvn --batch-mode -P shared-dll package
          cp target/libvcell.dll ../libvcell/_internal/libs
        if: ${{ startsWith(matrix.os, 'windows') }}

      - name: Run tests
        run: poetry run pytest tests --cov --cov-config=pyproject.toml --cov-report=xml

      - name: Check typing
        run: poetry run mypy

      - name: Upload coverage reports to Codecov with GitHub Action on Python 3.11
        uses: codecov/codecov-action@v4
        if: ${{ matrix.python-version == '3.11' }}

      - name: Setup tmate
        if: failure()
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env

      - name: Check if documentation can be built
        run: poetry run mkdocs build -s
